POST http://localhost:8080/media
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="boocover.jpg"
Content-Type: image/jpeg

< ./media.jpg
--WebAppBoundary--

###
