###

GET https://jdbc-final.herokuapp.com/books

###

GET https://jdbc-final.herokuapp.com/books/3

###

GET https://jdbc-final.herokuapp.com/books/search?name=Подросток&author=Достоевский

###

POST https://jdbc-final.herokuapp.com/books
Content-Type: application/json

{
  "id": 0,
  "producer_id": 1,
  "name": "Бородино",
  "price": 180,
  "author": "Лермонтов",
  "weight": 230

}

###

POST https://jdbc-final.herokuapp.com/books
Content-Type: application/json

{
  "id": 2,
  "producer_id": 2,
  "name": "Анна Каренина",
  "price": 500,
  "author": "Толстой",
  "weight": 300

}

###

DELETE https://jdbc-final.herokuapp.com/books/5

###
GET https://jdbc-final.herokuapp.com/customers

###

GET https://jdbc-final.herokuapp.com/customers/2

###

GET https://jdbc-final.herokuapp.com/customers/search?name=Иван

###

POST https://jdbc-final.herokuapp.com/customers
Content-Type: application/json

{
  "id": 0,
  "name": "Николай",
  "email": "kolya@mail.ru",
  "delivery_address": "Санкт-Петербург"


}

###

POST https://jdbc-final.herokuapp.com/customers
Content-Type: application/json

{
  "id": 2,
  "name": "Анна",
  "email": "anna@mail.ru",
  "delivery_address": "Уфа"

}

###

DELETE https://jdbc-final.herokuapp.com/customers/5

###

GET https://jdbc-final.herokuapp.com/orders

###

POST https://jdbc-final.herokuapp.com/media
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="boocover.jpg"
Content-Type: image/jpeg

< ./media.jpg
--WebAppBoundary--
